name: 🪲 Bug Report
description: Report a reproducible bug in Baserow.
labels: ["needs feedback ⚠️", "bug 🪲"]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question about Baserow, please post it on the community forum:
        https://community.baserow.io/

  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description: A brief description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps required to reproduce the error.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: What currently happens in Baserow.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Describe how you're running Baserow.
      placeholder: |
        - Operating System: Windows/Ubuntu/Mac/etc.
        - Web Browser: Chrome / Firefox / Edge / Safari
        - Deployment Type: baserow.io / docker / other
        - Baserow Version: 1.8 / 1.7 / develop
